site_name: TenKo
repo_url: https://github.com/cantpr09ram/tenko/

theme:
  name: material

nav:
  - Home:
      - getting start: index.md
      - if you're dev: dev.md
      - if you're user: user.md
